// Username and password constants for our OpenSearch master user.
// Note that the actual password is generated by AWS secret.
export const OPENSEARCH_DASHBOARD_USERNAME_KEY = "username";
export const OPENSEARCH_DASHBOARD_USERNAME = "nodUser";
export const OPENSEARCH_DASHBOARD_PASSWORD_KEY = "password";
